### ISSUE TITLE
不理解怎么用run_classifier来生成对话

### ISSUE THREAD

**Issue by aguang1201** [GaoQ1/rasa-bert-finetune#1]
感谢up主的传送门。有点不懂得地方想请教。对话系统是怎么用run_classifier实现对话生成的呢？我对run_classifier的理解是对输入的句子做分类。对话系统中，输入是提问句，输出是生成的回答句，而不是分类。所以我不理解是怎么用分类任务来做生成回答的。也看了您发的rasa对话系统踩坑记（八），还是没找到答案。能不能给些提示，谢谢。
ps：刚上传了3个小时的新鲜代码。：）

**Comment by GaoQ1** [comment]
这里的run_classifier是用来做意图分类的微调的

**Comment by aguang1201** [comment]
看了demo好像提问比较多，当用户提问时，下句是怎么生成的呢？难道不是生成回答而是检索回答？

**Comment by GaoQ1** [comment]
nlg这块，是在rasa-core中实现的，现在还是用的根据nlu的意图和slot从template中随机选取句子回答的。

**Comment by aguang1201** [comment]
@GaoQ1 感谢您的解答。基本理解了楼主的意思。可能是因为这是个任务型聊天机器人，所以检索生成问题或者答案就可以了。我想做个非人物型插科打诨漫天扯淡型机器人（类似微软小冰），所以需要生成式回答。之前用seq2seq做了一个，现在想用BERT架构实现。
